### ISSUE TITLE
MaplySticker grouped using multiple drawables

### ISSUE THREAD

**Issue by bryanheitman** [mousebird-consulting-inc/WhirlyGlobe#803] opened 2016-12-05 15:06 UTC
Opening issue per SteveG.

**Comment by mousebird** [comment] 2016-12-05 15:29
The problem is if you add 300 of them you get 300 drawables.  It needs to consolidate them like we do everything else.

**Comment by TimSylvester-mousebird** [comment] 2021-06-23 18:24
Fixed in 3.0.  `addStickers` takes a collection of `MaplySticker` and returns a single `MaplyComponentObject`.

**Closed by TimSylvester-mousebird** 2021-06-23 18:24 UTC
Labels: feature request
